export const EventName = {
  RESOURCE_CREATED: 'RESOURCE_CREATED',
  RESOURCE_UPDATED: 'RESOURCE_UPDATED',
  RESOURCE_DELETED: 'RESOURCE_DELETED',
  RESOURCE_MOVED: 'RESOURCE_MOVED',
  CATEGORY_ASSIGNED: 'CATEGORY_ASSIGNED',
  WORKSPACE_CREATED: 'WORKSPACE_CREATED',
  WORKSPACE_RENAMED: 'WORKSPACE_RENAMED',
  WORKSPACE_ARCHIVED: 'WORKSPACE_ARCHIVED',
  WORKSPACE_DELETED: 'WORKSPACE_DELETED',
  SESSION_SAVED: 'SESSION_SAVED',
  SESSION_RESTORED: 'SESSION_RESTORED',
  SESSION_DELETED: 'SESSION_DELETED',
  IMPORT_COMPLETED: 'IMPORT_COMPLETED',
  IMPORT_FAILED: 'IMPORT_FAILED',
  EXPORT_COMPLETED: 'EXPORT_COMPLETED',
} as const;

export type EventName = typeof EventName[keyof typeof EventName];
